name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest mypy
      - name: Run mypy
        run: mypy --strict src/app/batch_manager.py src/app/openai_batch.py src/app/file_processor.py src/utils/*.py src/interfaces/streamlit/main.py
      - name: Run tests
        run: pytest
